#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: ./nb/common.ipynb
from xs_lib.common import Export_notebook
export_notebook = Export_notebook('jupyter_dev_template', working_dir_tag='notebooks')