#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: ./nb/template.ipynb
import sys
if __name__ == '__main__': sys.path.append('..')
from jupyter_dev_template.common import export_notebook